live_config_reload = true

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#000000"
foreground = "#ebdbb2"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "SFMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Heavy Italic"

[font.glyph_offset]
x = 0
y = 2

[font.italic]
family = "SFMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "SFMono Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 5

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.7

[window.padding]
x = 5
y = 5

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"
