[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "kick"

[[session]]
name = "mlb"
path = "~/side/MLB-StatsAPI/"
startup_command = "python hr-k-draft.py"

[[session]]
name = "platform node / java"
path = "~/code/platform_work"
startup_command = ""

[[session]]
name = "Rest"
path = "~/code/rest"
startup_command = "kick"
