[[session]]
name = "Dotfiles"
path = "~/dotfiles"
startup_command = "kick"

[[session]]
name = "MLB"
path = "~/side/MLB-StatsAPI/"
startup_command = "python hr-k-draft.py"

[[session]]
name = "Local"
path = "~/code/platform_work"
startup_command = ""

[[session]]
name = "Rest"
path = "~/code/rest"
startup_command = "kick"
