# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

export EDITOR='nvim'

ZSH_THEME=""

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions zsh-vi-mode)


# user config

# sources zsh file
source $ZSH/oh-my-zsh.sh

# sources the alias file
source ~/dotfiles/config/aliases

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# ~/.tmux/plugins
export PATH=$HOME/.tmux/plugins/t-smart-tmux-session-manager/bin:$PATH

# Star Ship
eval "$(starship init zsh)"

# zoxide init
eval "$(zoxide init zsh)"

# fnm
export PATH=/home/$USER/.fnm:$PATH
eval "$(fnm env --use-on-cd --version-file-strategy=recursive)"

# code to have multiple configs
# alias kick="NVIM_APPNAME=kickstart nvim"
#
# function nvims() {
#   items=("default" "kickstart" "LazyVim" "NvChad" "AstroNvim")
#   config=$(printf "%s\n" "${items[@]}" | fzf --prompt=" Neovim Config  " --height=~50% --layout=reverse --border --exit-0)
#   if [[ -z $config ]]; then
#     echo "Nothing selected"
#     return 0
#   elif [[ $config == "default" ]]; then
#     config=""
#   fi
#   NVIM_APPNAME=$config nvim $@
# }

now() {
    timestamp=$(date +"%Y-%m-%d %H:%M:%S")
    echo "$timestamp" | xclip -selection clipboard
    echo "Timestamp copied to clipboard: $timestamp"
}

# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export PATH="/usr/local/opt/python/libexec/bin:$PATH"

# nvm 
export NVM_DIR="$HOME/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# open nvim directly into telescope
function fuzzy_nvim_start {
    if [ "$#" -eq 0 ]; then
        kick +'Telescope find_files hidden=false layout_config={height=0.9}'
    elif [ -d "$1" ]; then
        kick +"Telescope find_files hidden=false layout_config={height=0.9} cwd=$1"
    else
        kick $@
    fi
}

export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"
export PATH="$PATH":~/dotfiles/config/scripts
export GH_DASH_CONFIG="$HOME/.config/gh-dash/config.yml"
export GOPATH=$HOME/go
export PATH="$PATH:$GOPATH/bin"

